pub fn get_error_msg(code: i32) -> &'static str {
    match code {
        0 => "XL_DL_ERROR_SUCCESS",
        1 => "XL_DL_ERROR_FAILED",
        9101 => "XL_DL_ERROR_ALREADY_INIT",
        9102 => "XL_DL_ERROR_SDK_NOT_INIT",
        9103 => "XL_DL_ERROR_TASK_ALREADY_EXIST",
        9104 => "XL_DL_ERROR_TASK_NOT_EXIST",
        9105 => "XL_DL_ERROR_TASK_ALREADY_STOPPED",
        9106 => "XL_DL_ERROR_TASK_ALREADY_RUNNING",
        9107 => "XL_DL_ERROR_TASK_NOT_START",
        9108 => "XL_DL_ERROR_TASK_STILL_RUNNING",
        9109 => "XL_DL_ERROR_FILE_EXISTED",
        9110 => "XL_DL_ERROR_DISK_FULL",
        9111 => "XL_DL_ERROR_TOO_MUCH_TASK",
        9112 => "XL_DL_ERROR_PARAM_ERROR",
        9113 => "XL_DL_ERROR_SCHEMA_NOT_SUPPORT",
        9114 => "XL_DL_ERROR_DYNAMIC_PARAM_FAIL",
        9115 => "XL_DL_ERROR_CONTINUE_NO_NAME",
        9116 => "XL_DL_ERROR_APPNAME_APPKEY_ERROR",
        9117 => "XL_DL_ERROR_CREATE_THREAD_ERROR",
        9118 => "XL_DL_ERROR_TASK_FINISH",
        9119 => "XL_DL_ERROR_TASK_NOT_RUNNING",
        9120 => "XL_DL_ERROR_TASK_NOT_IDLE",
        9121 => "XL_DL_ERROR_TASK_TYPE_NOT_SUPPORT",
        9122 => "XL_DL_ERROR_ADD_RESOURCE_ERROR",
        9123 => "XL_DL_ERROR_FUNCTION_NOT_SUPPORT",
        9124 => "XL_DL_ERROR_ALREADY_HAS_FILENAME",
        9125 => "XL_DL_ERROR_FILE_NAME_TOO_LONG",
        9126 => "XL_DL_ERROR_ONE_PATH_LEVEL_NAME_TOO_LONG",
        9127 => "XL_DL_ERROR_FULL_PATH_NAME_TOO_LONG",
        9128 => "XL_DL_ERROR_FULL_PATH_NAME_OCCUPIED",
        9129 => "XL_DL_ERROR_TASK_NO_FILE_NAME",
        9130 => "XL_DL_ERROR_NOT_WIFI_MODE",
        9131 => "XL_DL_ERROR_SPEED_LIMIT_TO_SMALL",
        9501 => "XL_DL_ERROR_TASK_CONTROL_STRATEGY",
        9502 => "XL_DL_ERROR_URL_IS_TOO_LONG",
        9503 => "XL_DL_ERROR_FILE_DELETE_FAIL",
        9504 => "XL_DL_ERROR_FILE_NOT_EXIST",
        9505 => "XL_DL_ERROR_INFO_NAME_NOT_SUPPORT",
        9601 => "XL_DL_ERROR_MEMORY_TOO_SMALL",
        9602 => "XL_DL_ERROR_AUTH_TOKEN_VERIFY_FAILED",
        9603 => "XL_DL_ERROR_AUTH_SCOPE_VERIFY_FAILED",
        9604 => "XL_DL_ERROR_AUTH_SESSION_ID_VERIFY_FAILED",
        9605 => "XL_DL_ERROR_AUTH_SESSION_ID_EXPIRED",
        9606 => "XL_DL_ERROR_AUTH_RES_HAS_NO_QUOTA",
        111085 => "XL_DL_ERROR_INSUFFICIENT_DISK_SPACE",
        111128 => "XL_DL_ERROR_OPEN_FILE_ERR",
        111136 => "XL_DL_ERROR_NO_DATA_PIPE",
        111151 => "XL_DL_ERROR_RESTRICTION",
        111152 => "XL_DL_ERROR_ACCOUNT_EXCEPTION",
        111153 => "XL_DL_ERROR_RESTRICTION_AREA",
        111154 => "XL_DL_ERROR_COPYRIGHT_BLOCKING",
        111155 => "XL_DL_ERROR_TYPE2_BLOCKING",
        111156 => "XL_DL_ERROR_TYPE3_BLOCKING",
        111176 => "XL_DL_ERROR_LONG_TIME_NO_RECV_DATA",
        119212 => "XL_DL_ERROR_TIME_OUT",
        999999 => "XL_DL_ERROR_TASK_STATUS_ERR",
        _ => "XL_DL_ERROR_UNKNOWN",
    }
}

pub fn get_task_state_msg(code: u8) -> &'static str {
    match code {
        0 => "L_DL_TASK_STATUS_UNKOWN",        //未知
        3 => "L_DL_TASK_STATUS_START_WAITING", //等待启动
        4 => "L_DL_TASK_STATUS_START_PENDING", //正在启动
        5 => "L_DL_TASK_STATUS_STARTED",       //正在运行
        6 => "L_DL_TASK_STATUS_STOP_PENDING",  //正在停止
        7 => "L_DL_TASK_STATUS_STOPED",        //已停止
        8 => "L_DL_TASK_STATUS_SUCCEEDED",     //任务已完成
        9 => "L_DL_TASK_STATUS_FAILED",        //任务失败
        _ => "XL_DL_ERROR_UNKNOWN",
    }
}
